### ISSUE TITLE
Link to Exchange Web Services is broken

### ISSUE THREAD

**Issue by Ebayironman** [techspence/EWSEmailAttachmentSaver#4]
Microsoft has stopped offering EWS through the download link posted at bottom of main page for EWSEmailAttachmentSaver

This url: http://www.microsoft.com/en-us/download/details.aspx?id=42951  winds up with resource no longer available.

New method to install EWS: You can download the API from nuget: https://www.nuget.org/packages/Microsoft.Exchange.WebServices/
No where near as convenient as the download link. 

You can still find the original download at some archives, ymmv.

**Comment by adonzelli** [comment]
Found this archive.org links that still work: 
https://web.archive.org/web/20200804152159/http://www.microsoft.com/en-us/download/details.aspx?id=42951 
https://web.archive.org/web/20200804152159/http://www.microsoft.com/en-us/download/confirmation.aspx?id=42951

**Comment by techspence** [comment]
Thanks @adonzelli for providing those web archive links!
